CREATE TABLE erp_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_customer_id VARCHAR(18) NOT NULL,
    business_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    billing_city VARCHAR(255)
);
