spring.application.name=integration-service

salesforce.oauth.token-url=${SALESFORCE_TOKEN_URL:}
salesforce.oauth.client-id=${SALESFORCE_CLIENT_ID:}
salesforce.oauth.client-secret=${SALESFORCE_CLIENT_SECRET:}

salesforce.api.version=${SALESFORCE_API_VERSION:}

logging.level.org.springframework.web.client=INFO

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

northstar.messaging.customer-sync.topic=${CUSTOMER_SYNC_TOPIC:northstar.customer-sync.v1}
northstar.messaging.customer-sync.acknowledgement-timeout=${CUSTOMER_SYNC_ACK_TIMEOUT:5s}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.spring.json.add.type.headers=false
