spring.application.name=integration-service

salesforce.oauth.token-url=${SALESFORCE_TOKEN_URL:}
salesforce.oauth.client-id=${SALESFORCE_CLIENT_ID:}
salesforce.oauth.client-secret=${SALESFORCE_CLIENT_SECRET:}
